### ISSUE TITLE
Discuss: Build Choices

### ISSUE THREAD

**Issue by dreafusion** [quicksolutions/starter-kit#4]
Webpack
Parcel
Roll up

**Comment by davidragsdale** [comment]
Roll up is better from a monorepo package standpoint (inlines dependencies in a clearer to trace way) but is not focused on browser needs. Parcel is MUCH simpler to use, uses HTML as an entry point, contains a livereload server, and is fast. Webpack is more flexible but not as easy to use, uses JS as the entry point (meaning JS imports your SCSS), contains a livereload server, and is also very fast. Webpack is used internally by most of framework command-line tooling (CRA, Nuxt, Next, etc.). For that reason I vote Webpack, although personally I prefer Parcel as a tool.

**Comment by davidragsdale** [comment]
@tmoserfusion this might be another case of requiring a good "guiding principle". How comfortable should we expect an average dev to be editing build configuration, or is it reasonable to say that the 80/20 rule would allow devs to phone-a-friend at first when it comes to ramping up on build configuration. Would they know what types of considerations fall under the build tool umbrella? Would they be expected to learn the solution themselves when a build tooling problem crops up, be taught the solution by another, or would it be reasonable for another dev to solve the problem and immediately extract themself?

**Comment by dreafusion** [comment]
Decided Webpack.
